from datetime import datetime

DATE_FMT = '%Y-%m-%d'
CURR_DATE = datetime.now().strftime(DATE_FMT)
ADDRESS_FORMAT = '{}, {}, {}'
MAKE = 'make'
MODEL = 'model'
TRIM = 'trim'
BODY_STYLE = 'bodyStyle'
YEAR = 'year'
PRICE = 'price'
MILEAGE = 'mileage'
FIRST_DATE = 'firstDate'
LAST_DATE = 'lastDate'
SELLER_ID = 'sellerID'
NAME = 'name'
DURATION = 'duration'
PHONE_NUMBER = 'phoneNumber'
STREET_ADDRESS = 'streetAddress'
CITY = 'city'
LISTING_ID = 'listingId'
STATE = 'state'
VIN = 'vin'
SELLER = 'seller'
VEHICLE = 'vehicle'
